### ISSUE TITLE
Game Crashes on Startup

### ISSUE THREAD

**Issue by kkeemmss2** [DrunkShulker/Bartender#11]
Bartender 1.14 crashes on startup and shows this:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Bartender (bartender)
Exit Code: -1

Bartender 1.13 Didnt have this problem
And i need the Killaura switch

![Issue](https://user-images.githubusercontent.com/71185072/92999262-32eb4d80-f528-11ea-905b-2bd4df6a7ea6.PNG)

**Comment by DrunkShulker** [comment]
pls tell me you removed the 1.1.3 from mods folder?

**Comment by DrunkShulker** [comment]
Try to remove the Bartender folder in .minecraft folder
