### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by SkywalkerSW5** [DrunkShulker/Bartender#20]
hewlooo

Im trying to build Bartender from source, but i keep getting this error

17:12:13.053 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:66: error: 'try' without 'catch', 'finally' or resource declarations
17:12:13.055 [ERROR] [system.err]         try {
17:12:13.056 [ERROR] [system.err]         ^
17:12:13.058 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:81: error: illegal start of type
17:12:13.059 [ERROR] [system.err]         }catch (Exception exception){
17:12:13.066 [ERROR] [system.err]          ^
17:12:13.067 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:81: error: ';' expected
17:12:13.067 [ERROR] [system.err]         }catch (Exception exception){
17:12:13.067 [ERROR] [system.err]                                    ^
17:12:13.068 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:84: error: <identifier> expected
17:12:13.068 [ERROR] [system.err]         System.out.println(NAME+" ipc init result: "+MAPPED_BUS_INITIALIZED);
17:12:13.068 [ERROR] [system.err]                           ^
17:12:13.068 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:84: error: <identifier> expected
17:12:13.069 [ERROR] [system.err]         System.out.println(NAME+" ipc init result: "+MAPPED_BUS_INITIALIZED);
17:12:13.069 [ERROR] [system.err]                                ^
17:12:13.069 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:87: error: <identifier> expected
17:12:13.069 [ERROR] [system.err]     	MINECRAFT_DIR = event.getModConfigurationDirectory().getParentFile().getAbsolutePath();
17:12:13.069 [ERROR] [system.err]     	             ^
17:12:13.070 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:88: error: illegal start of type
17:12:13.070 [ERROR] [system.err]     	if(!new File(Bartender.MINECRAFT_DIR + "/Bartender").exists()) {
17:12:13.070 [ERROR] [system.err]     	^
17:12:13.071 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:88: error: invalid method declaration; return type required
17:12:13.071 [ERROR] [system.err]     	if(!new File(Bartender.MINECRAFT_DIR + "/Bartender").exists()) {
17:12:13.071 [ERROR] [system.err]     	        ^
17:12:13.071 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:88: error: <identifier> expected
17:12:13.072 [ERROR] [system.err]     	if(!new File(Bartender.MINECRAFT_DIR + "/Bartender").exists()) {
17:12:13.072 [ERROR] [system.err]     	                                    ^
17:12:13.072 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:91: error: <identifier> expected
17:12:13.072 [ERROR] [system.err]     	BARTENDER_DIR = Bartender.MINECRAFT_DIR+"/Bartender";
17:12:13.072 [ERROR] [system.err]     	             ^
17:12:13.073 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:94: error: <identifier> expected
17:12:13.073 [ERROR] [system.err]     	ForgeLoadingScreen.modify();
17:12:13.073 [ERROR] [system.err]     	                         ^
17:12:13.073 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:95: error: <identifier> expected
17:12:13.095 [ERROR] [system.err]     	Config.load();
17:12:13.096 [ERROR] [system.err]     	           ^
17:12:13.096 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:96: error: <identifier> expected
17:12:13.097 [ERROR] [system.err]     	GuiConfig.load();
17:12:13.097 [ERROR] [system.err]     	              ^
17:12:13.097 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:97: error: <identifier> expected
17:12:13.098 [ERROR] [system.err]     	Preferences.apply();
17:12:13.098 [ERROR] [system.err]     	                 ^
17:12:13.101 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:100: error: <identifier> expected
17:12:13.101 [ERROR] [system.err]     	IMPACT_INSTALLED = ModsHelper.impactInstalled();
17:12:13.102 [ERROR] [system.err]     	                ^
17:12:13.102 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:101: error: <identifier> expected
17:12:13.102 [ERROR] [system.err]     	KAMI_INSTALLED = ModsHelper.kamiBlueInstalled();
17:12:13.102 [ERROR] [system.err]     	              ^
17:12:13.103 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:104: error: <identifier> expected
17:12:13.103 [ERROR] [system.err]     	PlayerFriends.loadImpactFriends();
17:12:13.103 [ERROR] [system.err]     	                               ^
17:12:13.105 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:107: error: invalid method declaration; return type required
17:12:13.105 [ERROR] [system.err]     	setCustomTitle();
17:12:13.107 [ERROR] [system.err]     	^
17:12:13.108 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:110: error: <identifier> expected
17:12:13.108 [ERROR] [system.err]     	Keybinds.register();
17:12:13.110 [ERROR] [system.err]     	                 ^
17:12:13.110 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:111: error: <identifier> expected
17:12:13.111 [ERROR] [system.err]         MinecraftForge.EVENT_BUS.register(new KeyInputHandler());
17:12:13.112 [ERROR] [system.err]                                          ^
17:12:13.113 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:111: error: illegal start of type
17:12:13.113 [ERROR] [system.err]         MinecraftForge.EVENT_BUS.register(new KeyInputHandler());
17:12:13.115 [ERROR] [system.err]                                           ^
17:12:13.115 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:112: error: <identifier> expected
17:12:13.117 [ERROR] [system.err]         MinecraftForge.EVENT_BUS.register(new ChatObserver());
17:12:13.119 [ERROR] [system.err]                                          ^
17:12:13.120 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:112: error: illegal start of type
17:12:13.120 [ERROR] [system.err]         MinecraftForge.EVENT_BUS.register(new ChatObserver());
17:12:13.120 [ERROR] [system.err]                                           ^
17:12:13.122 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:115: error: <identifier> expected
17:12:13.123 [ERROR] [system.err]         MinecraftForge.EVENT_BUS.register(new GuiHandler());
17:12:13.123 [ERROR] [system.err]                                          ^
17:12:13.123 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:115: error: illegal start of type
17:12:13.124 [ERROR] [system.err]         MinecraftForge.EVENT_BUS.register(new GuiHandler());
17:12:13.125 [ERROR] [system.err]                                           ^
17:12:13.126 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:118: error: <identifier> expected
17:12:13.126 [ERROR] [system.err]         CommandsRegistry.registerAll();
17:12:13.126 [ERROR] [system.err]                                     ^
17:12:13.126 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:121: error: <identifier> expected
17:12:13.126 [ERROR] [system.err]         ModulesRegistry.registerAll();
17:12:13.127 [ERROR] [system.err]                                    ^
17:12:13.127 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:125: error: class, interface, or enum expected
17:12:13.127 [ERROR] [system.err]     public void init(FMLInitializationEvent event){
17:12:13.127 [ERROR] [system.err]            ^
17:12:13.128 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:130: error: class, interface, or enum expected
17:12:13.132 [ERROR] [system.err]     public void postInit(FMLPostInitializationEvent event){
17:12:13.132 [ERROR] [system.err]            ^
17:12:13.133 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:132: error: class, interface, or enum expected
17:12:13.133 [ERROR] [system.err]     }
17:12:13.133 [ERROR] [system.err]     ^
17:12:13.136 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:137: error: class, interface, or enum expected
17:12:13.136 [ERROR] [system.err]     	if(IMPACT_INSTALLED) title = "Impact + Radium/"+title;
17:12:13.136 [ERROR] [system.err]     	^
17:12:13.137 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:138: error: class, interface, or enum expected
17:12:13.137 [ERROR] [system.err]     	if(KAMI_INSTALLED)title = "KAMI Blue + Radium/"+title;
17:12:13.137 [ERROR] [system.err]     	^
17:12:13.145 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:139: error: class, interface, or enum expected
17:12:13.145 [ERROR] [system.err]     	if(Minecraft.getMinecraft().getSession()!=null)
17:12:13.145 [ERROR] [system.err]     	^
17:12:13.146 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:142: error: class, interface, or enum expected
17:12:13.146 [ERROR] [system.err]         Display.setTitle(title);
17:12:13.146 [ERROR] [system.err]         ^
17:12:13.146 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/Bartender.java:143: error: class, interface, or enum expected
17:12:13.147 [ERROR] [system.err] 	}
17:12:13.147 [ERROR] [system.err] 	^
17:12:13.147 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:54: error: <identifier> expected
17:12:13.148 [ERROR] [system.err] 		GL11.glTranslated(-pos1.x, -pos1.y, -pos1.z);
17:12:13.148 [ERROR] [system.err] 		                 ^
17:12:13.148 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:54: error: illegal start of type
17:12:13.149 [ERROR] [system.err] 		GL11.glTranslated(-pos1.x, -pos1.y, -pos1.z);
17:12:13.149 [ERROR] [system.err] 		                  ^
17:12:13.149 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:55: error: <identifier> expected
17:12:13.149 [ERROR] [system.err] 		GL11.glDisable(GL11.GL_LIGHTING);
17:12:13.150 [ERROR] [system.err] 		              ^
17:12:13.151 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:55: error: <identifier> expected
17:12:13.151 [ERROR] [system.err] 		GL11.glDisable(GL11.GL_LIGHTING);
17:12:13.152 [ERROR] [system.err] 		                               ^
17:12:13.152 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:56: error: <identifier> expected
17:12:13.152 [ERROR] [system.err] 		GL11.glDisable(GL11.GL_TEXTURE_2D);
17:12:13.152 [ERROR] [system.err] 		              ^
17:12:13.153 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:56: error: <identifier> expected
17:12:13.153 [ERROR] [system.err] 		GL11.glDisable(GL11.GL_TEXTURE_2D);
17:12:13.153 [ERROR] [system.err] 		                                 ^
17:12:13.153 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:57: error: <identifier> expected
17:12:13.153 [ERROR] [system.err] 		GL11.glDisable(GL11.GL_DEPTH_TEST); 
17:12:13.154 [ERROR] [system.err] 		              ^
17:12:13.158 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:57: error: <identifier> expected
17:12:13.159 [ERROR] [system.err] 		GL11.glDisable(GL11.GL_DEPTH_TEST); 
17:12:13.160 [ERROR] [system.err] 		                                 ^
17:12:13.160 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:58: error: <identifier> expected
17:12:13.161 [ERROR] [system.err] 		GL11.glEnable(GL11.GL_BLEND);
17:12:13.161 [ERROR] [system.err] 		             ^
17:12:13.161 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:58: error: <identifier> expected
17:12:13.161 [ERROR] [system.err] 		GL11.glEnable(GL11.GL_BLEND);
17:12:13.161 [ERROR] [system.err] 		                           ^
17:12:13.162 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:59: error: <identifier> expected
17:12:13.162 [ERROR] [system.err] 		GL11.glLineWidth(3f);
17:12:13.163 [ERROR] [system.err] 		                ^
17:12:13.164 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:59: error: illegal start of type
17:12:13.164 [ERROR] [system.err] 		GL11.glLineWidth(3f);
17:12:13.164 [ERROR] [system.err] 		                 ^
17:12:13.165 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:60: error: <identifier> expected
17:12:13.165 [ERROR] [system.err] 		GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
17:12:13.165 [ERROR] [system.err] 		                ^
17:12:13.165 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:60: error: <identifier> expected
17:12:13.166 [ERROR] [system.err] 		GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
17:12:13.166 [ERROR] [system.err] 		                                  ^
17:12:13.166 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:60: error: <identifier> expected
17:12:13.166 [ERROR] [system.err] 		GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
17:12:13.167 [ERROR] [system.err] 		                                                               ^
17:12:13.169 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:63: error: illegal start of type
17:12:13.169 [ERROR] [system.err] 		for (Entity e:EntityRadar.nearbyMobs()) {
17:12:13.169 [ERROR] [system.err] 		^
17:12:13.170 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:63: error: ';' expected
17:12:13.170 [ERROR] [system.err] 		for (Entity e:EntityRadar.nearbyMobs()) {
17:12:13.170 [ERROR] [system.err] 		             ^
17:12:13.170 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:63: error: <identifier> expected
17:12:13.171 [ERROR] [system.err] 		for (Entity e:EntityRadar.nearbyMobs()) {
17:12:13.171 [ERROR] [system.err] 		                                    ^
17:12:13.171 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:63: error: ';' expected
17:12:13.172 [ERROR] [system.err] 		for (Entity e:EntityRadar.nearbyMobs()) {
17:12:13.172 [ERROR] [system.err] 		                                      ^
17:12:13.173 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:74: error: <identifier> expected
17:12:13.173 [ERROR] [system.err] 		GL11.glEnable(GL11.GL_LIGHTING);
17:12:13.173 [ERROR] [system.err] 		             ^
17:12:13.174 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:74: error: <identifier> expected
17:12:13.174 [ERROR] [system.err] 		GL11.glEnable(GL11.GL_LIGHTING);
17:12:13.174 [ERROR] [system.err] 		                              ^
17:12:13.175 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:75: error: <identifier> expected
17:12:13.175 [ERROR] [system.err] 		GL11.glPopAttrib();
17:12:13.175 [ERROR] [system.err] 		                ^
17:12:13.176 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:76: error: <identifier> expected
17:12:13.176 [ERROR] [system.err] 		GL11.glPopMatrix();
17:12:13.178 [ERROR] [system.err] 		                ^
17:12:13.178 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:79: error: class, interface, or enum expected
17:12:13.179 [ERROR] [system.err] 	private static float pTicks() {
17:12:13.179 [ERROR] [system.err] 	               ^
17:12:13.179 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:81: error: class, interface, or enum expected
17:12:13.179 [ERROR] [system.err] 		else return Minecraft.getMinecraft().getRenderPartialTicks();
17:12:13.180 [ERROR] [system.err] 		^
17:12:13.181 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:82: error: class, interface, or enum expected
17:12:13.181 [ERROR] [system.err] 	}
17:12:13.181 [ERROR] [system.err] 	^
17:12:13.182 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:86: error: class, interface, or enum expected
17:12:13.183 [ERROR] [system.err] 		GL11.glBegin(GL11.GL_LINE_STRIP);
17:12:13.183 [ERROR] [system.err] 		^
17:12:13.183 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:88: error: class, interface, or enum expected
17:12:13.184 [ERROR] [system.err] 		GL11.glVertex3d(pos1.x, pos1.y, pos1.z);
17:12:13.184 [ERROR] [system.err] 		^
17:12:13.187 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:89: error: class, interface, or enum expected
17:12:13.187 [ERROR] [system.err] 		GL11.glVertex3d(pos2.x, pos2.y, pos2.z);
17:12:13.189 [ERROR] [system.err] 		^
17:12:13.191 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:90: error: class, interface, or enum expected
17:12:13.191 [ERROR] [system.err] 		GL11.glEnd();
17:12:13.192 [ERROR] [system.err] 		^
17:12:13.195 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/client/module/Tracers.java:91: error: class, interface, or enum expected
17:12:13.196 [ERROR] [system.err] 	}
17:12:13.196 [ERROR] [system.err] 	^
17:12:13.197 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/util/kami/BlockUtils.java:150: error: unclosed comment
17:12:13.197 [ERROR] [system.err]         /**
17:12:13.197 [ERROR] [system.err]         ^
17:12:13.197 [ERROR] [system.err] /home/skywalkersw5/.stuf/Bartender/build/sources/main/java/com/drunkshulker/bartender/util/kami/BlockUtils.java:222: error: reached end of file while parsing
17:12:13.198 [ERROR] [system.err]         }
17:12:13.198 [ERROR] [system.err]          ^
17:12:13.199 [ERROR] [system.err] 68 errors

lovely lil message huh?

the first time i tried to build, i used OpenJDK 8, and the second time i used OpenJDK 14. Both had this same issue. I also tried removing the part in Bartender.java that had the /tmp part since linux has one, ut that didnt do anything. I dont know java so if this is a noob error then my apologies :)

**Comment by destroyer4teen** [comment]
idk what this means, but if it is a coustom schematic, you might just want to download the schemtica mod ur self and put it in there

**Comment by DrunkShulker** [comment]
This looks like your workspace isnt setup correctly. Try running `init`, `setupDecompWorkspace` and `genIntellijRuns` again

**Comment by DrunkShulker** [comment]
Closed due to inactivity
