### ISSUE TITLE
When I connect into a server, I crash.

### ISSUE THREAD

**Issue by 2ezz** [DrunkShulker/Bartender#22]
The game crashed whilst unexpected error
Error: java.lang.IncompatibleClassChangeError: Expected non-static field baritone.api.utils.BetterBlockPos.field_177990_b
Exit Code: -1

I've uninstalled and reinstalled, deleted the tmp file and remade it, deleted the Bartender folder as well.

**Comment by DrunkShulker** [comment]
You have installed Impact (or some other client with baritone) wrong. Please create a fresh instance of minecraft and make sure impact is installed as a forge mod. Tutorial here: https://github.com/DrunkShulker/Bartender/wiki#install
