### ISSUE TITLE
I crash when I move too much

### ISSUE THREAD

**Issue by salsasl** [DrunkShulker/Bartender#25]
I have future installed into forge, but this happened even before I had that. Crash logs: 

Error: java.lang.IncompatibleClassChangeError: Expected non-static field baritone.api.utils.BetterBlockPos.field_177990_b
Exit Code: -1

**Comment by DrunkShulker** [comment]
This is due to baritone installation. You might have used Impact or some other client with baritone before. You have to create a fresh install for this error to go away. Follow this tutorial: https://github.com/DrunkShulker/Bartender/wiki

**Comment by salsasl** [comment]
Thanks. I just installed multimc and ran it off there.
