### ISSUE TITLE
Safetotem and Bodyguard

### ISSUE THREAD

**Issue by salsasl** [DrunkShulker/Bartender#28]
When I use safetotem and it swaps at 3, It doesn't automatically go to the previous slot. Is this normal behavior?

And for Bodyguard, when I press "takeoff" in group menu, only one try's to take off and it cant, and the other one doesn't even try. (I should also mention that I am only using bartender client.)

**Comment by DrunkShulker** [comment]
Yes, safe totem does not equip previous item after swap. Maybe I should add that in future updates.

There are couple of things that could cause takeoff to fail. I have noticed that lately the server lag itself has been so bad it prevents takeoff. I'll investigate this one.

For more questions my discord is DrunkShulker#8259
