### ISSUE TITLE
Just a question for Mac users

### ISSUE THREAD

**Issue by RedGunn911** [DrunkShulker/Bartender#29]
In windows, you access the hack via right control right? Now I'm on a Mac and I don't know how to access the hack. Is there any way I can access the client on Mac? Thanks

**Comment by DrunkShulker** [comment]
Go to pause menu -> options -> controls. There you can set the key. Please read the wiki: https://github.com/DrunkShulker/Bartender/wiki

**Comment by RedGunn911** [comment]
thanks
