### ISSUE TITLE
Minecraft keeps crashing but i have a temp file in my cdrive please help

### ISSUE THREAD

**Issue by destroyer4teen** [DrunkShulker/Bartender#6]
i have a temp file, and no one has helped me, the only reason it should crash is if i dont have a temp file, i downloaded forge and put it the the mods folder as well as impact

**Comment by destroyer4teen** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BartenderMixinLoader (xyz-bartender-1.1.3 (1).jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 9/11/20 10:27 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at io.mappedbus.MappedBusReader.next(MappedBusReader.java:138)
	at com.drunkshulker.bartender.client.ipc.IPCHandler.listener(IPCHandler.java:34)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_33_IPCHandler_listener_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 158512264 bytes (151 MB) / 536870912 bytes (512 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | bartender | 1.1.3        | xyz-bartender-1.1.3 (1).jar   | None                                     |

	Loaded coremods (and transformers): 
BartenderMixinLoader (xyz-bartender-1.1.3 (1).jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14736 Compatibility Profile Context 20.8.2 27.20.2001.16003' Renderer: 'AMD Radeon RX 5700 XT'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: AMD Radeon RX 5700 XT GL version 4.6.14736 Compatibility Profile Context 20.8.2 27.20.2001.16003, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz

**Comment by DrunkShulker** [comment]
You are missing the tmp folder.
1. make sure you created a folder, not a file
2. make sure its named `tmp` not `temp`

I assume you are on Windows.

**Comment by destroyer4teen** [comment]
Btw, is it true that you tokkened it. Or backdoored the client

**Comment by TudbuT** [comment]
Nope, its not true
